-- ─── 1. FIX STOCK MOVEMENTS & COUNTING ──────────────────────────────────
-- Add 'notes' column if missing (fixes 400 Bad Request error)
ALTER TABLE public.stock_movements ADD COLUMN IF NOT EXISTS notes text;

-- Upgrade process_stock_count to handle notes correctly
CREATE OR REPLACE FUNCTION public.process_stock_count(
  p_location_id uuid,
  p_created_by uuid,
  p_notes text,
  p_items jsonb
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count_id uuid;
  v_item jsonb;
  v_product_id uuid;
  v_system_qty integer;
  v_counted_qty integer;
  v_final_qty integer;
  v_diff integer;
  v_adjustment_mode public.adjustment_type;
  v_business_id uuid;
BEGIN
  -- Get business_id from location
  SELECT business_id INTO v_business_id FROM public.locations WHERE id = p_location_id;

  -- Create master record
  INSERT INTO public.stock_counts (
    business_id, stock_name, location_id, created_by, notes
  ) VALUES (
    v_business_id, 'Adj - ' || TO_CHAR(NOW(), 'YYYY-MM-DD HH24:MI'), p_location_id, p_created_by, NULLIF(p_notes, '')
  ) RETURNING id INTO v_count_id;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_product_id      := (v_item ->> 'product_id')::uuid;
    v_counted_qty     := (v_item ->> 'counted_quantity')::integer;
    v_adjustment_mode  := (v_item ->> 'adjustment_mode')::public.adjustment_type;
    
    -- Get current stock
    SELECT quantity INTO v_system_qty FROM public.product_stocks WHERE product_id = v_product_id AND location_id = p_location_id;
    v_system_qty := COALESCE(v_system_qty, 0);

    -- Calculate delta
    IF v_adjustment_mode = 'add' THEN
      v_final_qty := v_system_qty + v_counted_qty;
      v_diff := v_counted_qty;
    ELSE
      v_final_qty := v_system_qty - v_counted_qty;
      v_diff := -v_counted_qty;
    END IF;

    -- Update records
    INSERT INTO public.stock_count_items (
      business_id, stock_count_id, product_id, system_quantity, adjustment_mode, counted_quantity, final_quantity
    ) VALUES (
      v_business_id, v_count_id, v_product_id, v_system_qty, v_adjustment_mode, v_counted_qty, v_final_qty
    );

    INSERT INTO public.product_stocks (business_id, product_id, location_id, quantity)
    VALUES (v_business_id, v_product_id, p_location_id, v_final_qty)
    ON CONFLICT (product_id, location_id) DO UPDATE SET quantity = EXCLUDED.quantity;

    -- Update Global Total
    UPDATE public.products p
    SET stock_quantity = (SELECT COALESCE(SUM(quantity), 0) FROM public.product_stocks WHERE product_id = p.id)
    WHERE id = v_product_id AND business_id = v_business_id;

    -- Record Movement (NOW INCLUDES NOTES COLUMN)
    IF v_diff != 0 THEN
       INSERT INTO public.stock_movements (
        business_id, product_id, user_id, movement_type, quantity, location_id, reference_type, reference_id, notes
      ) VALUES (
        v_business_id, v_product_id, p_created_by, 'count', v_diff, p_location_id, 'stock_count', v_count_id, COALESCE(p_notes, 'Standard Adjustment')
      );
    END IF;
  END LOOP;

  RETURN v_count_id;
END;
$$;

-- ─── 2. HUMAN READABLE IDS FOR PURCHASES ──────────────────────────────
-- Add purchase_number column if it doesn't exist
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='purchases' AND column_name='purchase_number') THEN
        ALTER TABLE public.purchases ADD COLUMN purchase_number bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1001);
    END IF;
END $$;

-- ─── 3. REFUND APPROVAL WORKFLOW ───────────────────────────────────────
-- Add status and approval tracking to sale_returns
ALTER TABLE public.sale_returns ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending_approval';
ALTER TABLE public.sale_returns ADD COLUMN IF NOT EXISTS approved_by uuid REFERENCES public.users(id);

-- Update return items to include approval tracking
ALTER TABLE public.sale_return_items ADD COLUMN IF NOT EXISTS approved boolean DEFAULT false;

-- Modified process_sale_return to enforce approval for cashiers
CREATE OR REPLACE FUNCTION public.process_sale_return(
  p_sale_id       uuid,
  p_created_by    uuid,
  p_reason        text,
  p_refund_method text,
  p_notes         text,
  p_items         jsonb
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_return_id   uuid;
  v_item        jsonb;
  v_total       numeric := 0;
  v_business_id uuid;
  v_location_id uuid;
  v_user_role   text;
  v_status      text;
BEGIN
  -- 1. Identify business and user role
  SELECT business_id, location_id INTO v_business_id, v_location_id FROM public.sales WHERE id = p_sale_id;
  SELECT role INTO v_user_role FROM public.users WHERE id = p_created_by;

  -- 2. Determine initial status
  IF v_user_role = 'cashier' THEN
    v_status := 'pending_approval';
  ELSE
    v_status := 'completed';
  END IF;

  -- 3. Sum refund
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
    v_total := v_total + (v_item->>'unit_price')::numeric * (v_item->>'quantity')::numeric;
  END LOOP;

  -- 4. Create record
  INSERT INTO public.sale_returns (
    business_id, sale_id, created_by, reason,
    refund_method, refund_amount, notes, status
  ) VALUES (
    v_business_id, p_sale_id, p_created_by, p_reason,
    p_refund_method, v_total, p_notes, v_status
  ) RETURNING id INTO v_return_id;

  -- 5. Always record returned items
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
    INSERT INTO public.sale_return_items (
      business_id, sale_return_id, sale_item_id,
      product_id, quantity, unit_price, refund_amount, restock, approved
    ) VALUES (
      v_business_id, v_return_id,
      NULLIF(v_item->>'sale_item_id','')::uuid,
      (v_item->>'product_id')::uuid,
      (v_item->>'quantity')::numeric,
      (v_item->>'unit_price')::numeric,
      (v_item->>'unit_price')::numeric * (v_item->>'quantity')::numeric,
      COALESCE((v_item->>'restock')::boolean, true),
      (v_status = 'completed')
    );
  END LOOP;

  -- 6. ONLY update stock if completed (Admin/Manager role)
  IF v_status = 'completed' THEN
     -- Note: For simplicity, we trigger the logic that restocks inventory here.
     -- Usually, we move this logic to an 'approve_return' function.
     PERFORM public.apply_return_restock(v_return_id);
  END IF;

  RETURN v_return_id;
END;
$$;

-- Helper to apply restock logic
CREATE OR REPLACE FUNCTION public.apply_return_restock(p_return_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_item record;
  v_location_id uuid;
  v_business_id uuid;
  v_created_by uuid;
BEGIN
  SELECT s.location_id, r.business_id, r.created_by INTO v_location_id, v_business_id, v_created_by
  FROM public.sale_returns r
  JOIN public.sales s ON s.id = r.sale_id
  WHERE r.id = p_return_id;

  FOR v_item IN SELECT * FROM public.sale_return_items WHERE sale_return_id = p_return_id AND restock = true LOOP
    UPDATE public.products SET stock_quantity = stock_quantity + v_item.quantity 
    WHERE id = v_item.product_id AND business_id = v_business_id;

    IF v_location_id IS NOT NULL THEN
      UPDATE public.product_stocks SET quantity = quantity + v_item.quantity 
      WHERE product_id = v_item.product_id AND location_id = v_location_id AND business_id = v_business_id;
    END IF;

    INSERT INTO public.stock_movements (business_id, product_id, user_id, movement_type, quantity, location_id, reference_type, reference_id)
    VALUES (v_business_id, v_item.product_id, v_created_by, 'in', v_item.quantity, v_location_id, 'sale_return', p_return_id);
  END LOOP;
END;
$$;
